import { DashboardShell } from '@/components/dashboard/dashboard-shell';
import { DashboardHeader } from '@/components/dashboard/header';
import { HealthScoreCard } from '@/components/dashboard/health-score-card';
import { MetricCard } from '@/components/dashboard/metric-card';
import { ExecutiveSummaryCard } from '@/components/dashboard/executive-summary-card';
import { CriticalFindingsCard } from '@/components/dashboard/critical-findings-card';
import { RecommendedActionsCard } from '@/components/dashboard/recommended-actions-card';

import { Activity, AlertTriangle, BookOpen, ClipboardList } from 'lucide-react';

export default function DashboardPage() {
	return (
		<DashboardShell>
			<DashboardHeader
				title="Executive Health"
				description="Daily operational intelligence across your customer support ecosystem."
			/>

			<div className="space-y-8">
				{/* Top Row */}
				<HealthScoreCard />

				{/* KPI Cards */}
				<div className="grid gap-6 md:grid-cols-2 xl:grid-cols-4">
					<MetricCard
						title="Critical Findings"
						value="3"
						description="Require immediate attention"
						icon={AlertTriangle}
					/>

					<MetricCard
						title="Knowledge Gaps"
						value="7"
						description="Missing documentation detected"
						icon={BookOpen}
					/>

					<MetricCard
						title="Recommended Actions"
						value="5"
						description="Generated by Sentinel AI"
						icon={ClipboardList}
					/>

					<MetricCard
						title="Health Reports"
						value="1"
						description="Generated this week"
						icon={Activity}
					/>
				</div>

				{/* Middle Row */}
				<div className="grid gap-6 lg:grid-cols-3">
					<div className="lg:col-span-2">
						<ExecutiveSummaryCard />
					</div>

					<CriticalFindingsCard />
				</div>

				{/* Bottom Row */}
				<RecommendedActionsCard />
			</div>
		</DashboardShell>
	);
}
