import { DashboardHeader } from '@/components/dashboard/header';
import { HealthScoreCard } from '@/components/dashboard/health-score-card';
import { MetricCard } from '@/components/dashboard/metric-card';
import { ExecutiveSummaryCard } from '@/components/dashboard/executive-summary-card';
import { CriticalFindingsCard } from '@/components/dashboard/critical-findings-card';
import { RecommendedActionsCard } from '@/components/dashboard/recommended-actions-card';
import { KnowledgeGapsMetric } from '@/components/dashboard/knowledge-gaps-metric';
import { TrendSummaryCard } from '@/components/dashboard/trend-summary-card';
import { AiExecutiveBriefCard } from '@/components/dashboard/ai-executive-brief-card';
import { ExecutiveTimelineCard } from '@/components/dashboard/executive-timeline-card';
import { RecentImprovementsCard } from '@/components/dashboard/recent-improvements-card';
import { OperationalSignalsCard } from '@/components/dashboard/operational-signals-card';
import { ConnectedSourcesCard } from '@/components/dashboard/connected-sources-card';
import { OnboardingBanner } from '@/components/dashboard/onboarding-banner';
import { FirstInsightCard } from '@/components/dashboard/first-insight-card';
import { EmptyState } from '@/components/dashboard/empty-state';

import { Activity, AlertTriangle, Building2, ClipboardList } from 'lucide-react';

import { getExecutiveDashboardData } from '@/lib/dashboard/dashboard';
import { getSignalsOverview, getConnectedSourcesOverview } from '@/lib/signals/data';
import { buildFirstInsightSummary } from '@/lib/signals/insight';

export default async function DashboardPage() {
	const [data, signalsOverview, connectedSources] = await Promise.all([
		getExecutiveDashboardData(),
		getSignalsOverview(),
		getConnectedSourcesOverview(),
	]);

	if (!data) {
		return (
			<>
				<DashboardHeader
					title="Executive Health"
					description="Daily operational intelligence across your customer support ecosystem."
				/>

				<div className="px-6 py-8 lg:px-8">
					<EmptyState
						icon={Building2}
						title="No organization found"
						description="Your account isn't linked to an organization yet. Once you're part of one, its Sentinel data will show up here."
					/>
				</div>
			</>
		);
	}

	const {
		healthScore,
		executiveSummary,
		findings,
		recommendations,
		knowledgeGaps,
		trend,
		counts,
		improvementHistory,
		timeline,
	} = data;

	const signals = signalsOverview?.signals ?? [];
	const patterns = signalsOverview?.patterns ?? [];

	// Phase 10C: a genuinely brand-new org (never synced anything, never had
	// a report) gets a calm, single next step instead of a wall of zeroes.
	if (signals.length === 0 && counts.healthReports === 0) {
		return (
			<>
				<DashboardHeader
					title="Executive Health"
					description="Daily operational intelligence across your customer support ecosystem."
				/>

				<div className="space-y-8 px-6 py-8 lg:px-8">
					<OnboardingBanner />
					<ConnectedSourcesCard sources={connectedSources ?? []} />
				</div>
			</>
		);
	}

	// Phase 10D/E/F: signals exist but Sentinel has never produced a report
	// yet -- the "first insight" moment, before the org has a baseline.
	const showFirstInsight = counts.healthReports === 0;
	const isBaseline = counts.healthReports === 1;

	return (
		<>
			<DashboardHeader
				title="Executive Health"
				description="Daily operational intelligence across your customer support ecosystem."
			/>

			<div className="space-y-8 px-6 py-8 lg:px-8">
				{showFirstInsight && <FirstInsightCard summary={buildFirstInsightSummary(signals, patterns)} />}

				{/* Trend */}
				<TrendSummaryCard trend={trend} />

				{/* Top Row */}
				<HealthScoreCard
					score={healthScore.score}
					previousScore={healthScore.previousScore}
					categories={healthScore.categories}
					isBaseline={isBaseline}
				/>

				{/* KPI Cards */}
				<div className="grid gap-6 md:grid-cols-2 xl:grid-cols-4">
					<MetricCard
						title="Critical Findings"
						value={String(counts.criticalFindings)}
						description="Require immediate attention"
						icon={AlertTriangle}
					/>

					<KnowledgeGapsMetric gaps={knowledgeGaps} />

					<MetricCard
						title="Recommended Actions"
						value={String(counts.recommendedActions)}
						description="Generated by Sentinel AI"
						icon={ClipboardList}
					/>

					<MetricCard
						title="Health Reports"
						value={String(counts.healthReports)}
						description="Generated to date"
						icon={Activity}
					/>
				</div>

				{/* Middle Row */}
				<div className="grid gap-6 lg:grid-cols-3">
					<div className="lg:col-span-2">
						<ExecutiveSummaryCard
							summary={executiveSummary.summary}
							keyTakeaway={executiveSummary.keyTakeaway}
							topRisks={executiveSummary.topRisks}
							potentialScoreGain={executiveSummary.potentialScoreGain}
						/>
					</div>

					<CriticalFindingsCard findings={findings} recommendations={recommendations} />
				</div>

				{/* AI Executive Brief */}
				<AiExecutiveBriefCard />

				{/* Action Plan */}
				<RecommendedActionsCard recommendations={recommendations} />

				{/* Improvement Loop (Phase 7) */}
				<div className="grid gap-6 lg:grid-cols-2">
					<RecentImprovementsCard improvements={improvementHistory} />
					<ExecutiveTimelineCard events={timeline} />
				</div>

				{/* Operational Signals (Phase 8) + Connected Sources (Phase 9) */}
				<div className="grid gap-6 lg:grid-cols-3">
					<div className="lg:col-span-2">
						<OperationalSignalsCard signals={signals} patterns={patterns} />
					</div>

					<ConnectedSourcesCard sources={connectedSources ?? []} />
				</div>
			</div>
		</>
	);
}
