import { DashboardHeader } from '@/components/dashboard/header';
import { HealthScoreCard } from '@/components/dashboard/health-score-card';
import { MetricCard } from '@/components/dashboard/metric-card';
import { ExecutiveSummaryCard } from '@/components/dashboard/executive-summary-card';
import { CriticalFindingsCard } from '@/components/dashboard/critical-findings-card';
import { RecommendedActionsCard } from '@/components/dashboard/recommended-actions-card';
import { KnowledgeGapsMetric } from '@/components/dashboard/knowledge-gaps-metric';
import { TrendSummaryCard } from '@/components/dashboard/trend-summary-card';
import { AiExecutiveBriefCard } from '@/components/dashboard/ai-executive-brief-card';
import { EmptyState } from '@/components/dashboard/empty-state';

import { Activity, AlertTriangle, Building2, ClipboardList } from 'lucide-react';

import { getExecutiveDashboardData } from '@/lib/dashboard/dashboard';

export default async function DashboardPage() {
	const data = await getExecutiveDashboardData();

	if (!data) {
		return (
			<>
				<DashboardHeader
					title="Executive Health"
					description="Daily operational intelligence across your customer support ecosystem."
				/>

				<div className="px-6 py-8 lg:px-8">
					<EmptyState
						icon={Building2}
						title="No organization found"
						description="Your account isn't linked to an organization yet. Once you're part of one, its Sentinel data will show up here."
					/>
				</div>
			</>
		);
	}

	const { healthScore, executiveSummary, findings, recommendations, knowledgeGaps, trend, counts } = data;

	return (
		<>
			<DashboardHeader
				title="Executive Health"
				description="Daily operational intelligence across your customer support ecosystem."
			/>

			<div className="space-y-8 px-6 py-8 lg:px-8">
				{/* Trend */}
				<TrendSummaryCard trend={trend} />

				{/* Top Row */}
				<HealthScoreCard
					score={healthScore.score}
					previousScore={healthScore.previousScore}
					categories={healthScore.categories}
				/>

				{/* KPI Cards */}
				<div className="grid gap-6 md:grid-cols-2 xl:grid-cols-4">
					<MetricCard
						title="Critical Findings"
						value={String(counts.criticalFindings)}
						description="Require immediate attention"
						icon={AlertTriangle}
					/>

					<KnowledgeGapsMetric gaps={knowledgeGaps} />

					<MetricCard
						title="Recommended Actions"
						value={String(counts.recommendedActions)}
						description="Generated by Sentinel AI"
						icon={ClipboardList}
					/>

					<MetricCard
						title="Health Reports"
						value={String(counts.healthReports)}
						description="Generated to date"
						icon={Activity}
					/>
				</div>

				{/* Middle Row */}
				<div className="grid gap-6 lg:grid-cols-3">
					<div className="lg:col-span-2">
						<ExecutiveSummaryCard
							summary={executiveSummary.summary}
							keyTakeaway={executiveSummary.keyTakeaway}
							topRisks={executiveSummary.topRisks}
							potentialScoreGain={executiveSummary.potentialScoreGain}
						/>
					</div>

					<CriticalFindingsCard findings={findings} />
				</div>

				{/* AI Executive Brief */}
				<AiExecutiveBriefCard />

				{/* Bottom Row */}
				<RecommendedActionsCard recommendations={recommendations} />
			</div>
		</>
	);
}
